```{r}
popSd <- function(x) sqrt(sum((x-mean(x))^2)/length(x))
pop <- c(1,2,3,4,5,5,7,6,8,9)
mean(pop);popSd(pop)
```

```{r}
quadruples <- expand.grid(pop,pop,pop,pop)
sampleMeans <- rowMeans(quadruples)
```

```{r}
hist(sampleMeans,breaks = seq(1,9,length.out = 32))
axis(1,at=1:9)
mean(sampleMeans)
popSd(sampleMeans)
```

```{r}
x <- seq(from=0, to=1, by=0.01)
y <- dbeta(x, 2, 5)
plot(x, y, type="l", main="Beta Distribution [0, 1]: shape1=2, shape2=5")
```

```{r}
alpha<- 2; beta<- 5
(beta.mean<- alpha/(alpha+beta))
(beta.var<- (alpha*beta)/((alpha+beta)^2*(alpha+beta+1)))
(beta.skew<-2*(beta-alpha)*sqrt(alpha+beta+1)/((alpha+beta+2)*sqrt(alpha*beta)))
```

```{r}
sam1<- matrix(rbeta(4*10000, 2, 5), nrow=10000, ncol=4)
sam2<- matrix(rbeta(256*10000,2, 5), nrow=10000, ncol=256)
mean.sam1<- rowMeans(sam1)
mean.sam2<- rowMeans(sam2)
```

```{r}
library(e1071)
mean(mean.sam1); sd(mean.sam1); skewness(mean.sam1)
mean(mean.sam2); sd(mean.sam2); skewness(mean.sam2)
```

```{r}
hist(mean.sam1, freq = F, breaks = 20, main="sample mean: n=4")
xRange <- seq(from=0, to=1,by=0.001)
lines(xRange, dnorm(xRange, mean=0.2850624, sd=0.08000857), col="red", lwd=2)
```

```{r}
hist(mean.sam2, freq = F, breaks = 20, main="sample mean: n=256")
xRange <- seq(from=0, to=1,by=0.001)
lines(xRange, dnorm(xRange, mean=0.2855376, sd=0.009989509), col="red", lwd=2)
```

```{r}
library(GISTools)
pro<-readShapePoly("Italy/Provinces.shp",IDvar="ID",proj4string=CRS("+proj=longlat"))
nei<- readShapePoly("Italy/Neighbors.shp", proj4string=CRS("+proj=longlat"))
pro.df <- as.data.frame(pro)
pro.bbox <- bbox(pro)
n <- length(pro)
idx <- sample(1:n, 50, replace = F)
pro.df[idx, "Sample"] <- "Sampled"
pro.df[-idx, "Sample"] <- "NotSampled"
pro.df$Sample <- as.factor(pro.df$Sample)
```

```{r}
library(TexMix)
plot(nei,axes = T,col=grey(0.9),border = "white", xlim=pro.bbox[1,],ylim=pro.bbox[2,])
mapColorQual(pro.df$Sample, pro,map.title=paste("Map of Italy Saples:",length(pro.df[idx, "Sample"]),"samples"),legend.title = "Sample",add.to.map=T)
```

