```{r}
pi.H0 <- 0.24
n <- 225
alpha <- 0.05
( x.hi <- qbinom(1-alpha,size=n, prob=pi.H0) ) # upper critical value
( pi.hi <- pbinom(x.hi,size=n, prob=pi.H0,lower.tail=FALSE) ) # exact upper alpha
```

```{r}
( pi.hi <- pbinom(x.hi-1,size=n, prob=pi.H0,lower.tail=FALSE) ) # exact upper alpha for pi.hi-1
( pi.hi <- pbinom(95-1,size=n, prob=pi.H0,lower.tail=FALSE) ) # p-value
```

```{r}
binom.test(95, 225, p=0.24, alternative = "greater")
```

```{r}
(p <- 95/225)
( z <- (p-pi.H0)/sqrt((pi.H0*(1-pi.H0))/n) )
pnorm(z, mean=0, sd=1, lower.tail = F)
```

```{r}
library(binom) # installation required
pi.H0 <- 0.24
pi.H1 <- seq(0.24, 0.90, by=0.01) # value range of pi under H1
beta <- 1 - binom.power(pi.H1, n=n, p=pi.H0, alpha=alpha,alternative = "greater", method="exact")
plot(pi.H1, beta, type="l", ylim=c(0,1),
xlab=expression(italic(pi[H[1]])), ylab=expression(beta-error),main="Beta Error Investigation" )
abline(v=pi.H0, col="tomato",lwd=2) # value pi under H0
abline(v=(x.hi)/n, col="salmon",lty=5) # critical values of pi
abline(h=0)
pi.H1[beta < 0.001]
```

```{r}
load("Part1Data.RData")
cor.test(cc1$X1, cc1$X2, alternative="greater", method="pearson")
```

```{r}
cor.test(cc2$X1, cc2$X2, alternative="two.sided", method="pearson")
```

```{r}
cor.test(cc3$X1, cc3$X2, alternative="less", method="pearson")
```

```{r}
pwr::pwr.r.test(r=0.5, sig.level=0.05, power=0.7)
pwr::pwr.r.test(r=0.5, sig.level=0.05, power=0.8)
pwr::pwr.r.test(r=0.5, sig.level=0.05, power=0.9)
```

```{r}
pwr::pwr.r.test(r=0.5, sig.level=0.10, n=35)
pwr::pwr.r.test(r=0.5, sig.level=0.05, n=35)
pwr::pwr.r.test(r=0.5, sig.level=0.01, n=35)
```

```{r}
qnorm(0.1,0,1,lower.tail = F)
```

```{r}
pnorm(3, 0, 1, lower.tail=F)
```

```{r}
pwr::pwr.t.test(d = 0.25, sig.level = 0.05, n=36,type = 'one.sample',alternative = 'two.sided')
pwr::pwr.t.test(d = 0.25, sig.level=0.01, n=36,type = 'one.sample',alternative = 'two.sided')
pwr::pwr.t.test(power = 0.5, sig.level=0.01, n=36,type = 'one.sample',alternative = 'two.sided')
pwr::pwr.t.test(power = 0.5, sig.level=0.01, n=144,type = 'one.sample',alternative = 'two.sided')
pwr::pwr.t.test(power = 0.99, sig.level=0.01,d = 0.50,type = 'one.sample', alternative = 'two.sided')
```

